Update to .NET 7 & NET Standard 2.1
bruceharrison1984/TinyHealthCheck pull request #3
Opened 2023-06-27 00:03 UTC by Twinki14

# Motivations
Maintenance 

# Modifications
- Update the tests projects to .NET 7
- Update `TinyHealthCheck` to .NET Standard 2.1

2023-06-27 00:33 UTC, Twinki14 commented
@bruceharrison1984 Heyo! This is ready, I can't find any breaking changes, and quite frankly this isn't even needed to fix anything broken but I wanted to contribute in some way for such a brilliantly small lib

All this does is updated various versions, packages, apply some formatting here and there, and add some notes about docker containers

2023-06-27 00:41 UTC, bruceharrison1984 commented
I appreciate the PR! I'll give this a look over tomorrow and let you know if anything needs to be changed. This would likely be a candidate for a 1.0.0 release since it's been pretty extensively battle tested at this point.

2023-06-27 14:08 UTC, bruceharrison1984 requested changes

2023-06-27 14:08 UTC, bruceharrison1984 commented on .github/workflows/devBuild.yml
Can we avoid changing the indention and whitespace, thus flagging unnecessary changes.

2023-06-27 14:08 UTC, bruceharrison1984 commented on .github/workflows/releaseBuild.yml
Can we avoid changing the indention and whitespace, thus flagging unnecessary changes.

2023-06-27 14:08 UTC, bruceharrison1984 commented on TinyHealthCheck/TinyHealthCheck.csproj
> +    <TargetFramework>netstandard2.1</TargetFramework>
This change actually carries some weight, and I am not a fan. I actually stopped at `netstandard2.0` to preserve backwards compatibility with .Net Framework. Moving to netstandard2.0 remove all .Net Framework compatibility, as well as several other implementations.

https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#select-net-standard-version

I would ask that you put this back to `netstandard2.0` to keep the compatibility as high as possible.

2023-06-28 05:01 UTC, Twinki14 commented on .github/workflows/devBuild.yml
Apologies, it's been adjusted

2023-06-28 05:01 UTC, Twinki14 commented on .github/workflows/releaseBuild.yml
Apologies, it's been adjusted

2023-06-28 05:01 UTC, Twinki14 commented on TinyHealthCheck/TinyHealthCheck.csproj
> +    <TargetFramework>netstandard2.1</TargetFramework>
Makes sense, revert back to 2.0

2023-06-28 05:04 UTC, Twinki14 commented
@bruceharrison1984 Ready for another review, I did also update the release workflow to use the newer `>> $GITHUB_OUTPUT`, so a minor additional update

2023-06-28 14:06 UTC, merged

2023-06-28 14:07 UTC, bruceharrison1984 commented
Merged. I'll cut a new release shortly. Thanks for the help!